#!/usr/bin/env bash
# shellcheck disable=SC2059
# shellcheck disable=SC2154
# shellcheck disable=SC2312

if [[ "${CHECK_BLOCKED_STRINGS}" = false ]]; then
    :
elif git-diff-index -pM --cached HEAD |
    # new additions only
    rg '^+' |
    # grep for blocked strings
    rg -i 'console\.|xxx:|\.only\('; then
    echo -e "\033[0;31mBlocking commit: a disallowed string was found\033[0m" >&2
    exit 1
fi

# run the repo's local pre-commit hooks if it exists
if [[ -f "$(git rev-parse --git-common-dir)/hooks/pre-commit" ]]; then
    "${GIT_DIR}"/hooks/pre-commit "$@"
fi
