#!/bin/sh

if git-diff-index -pM --cached HEAD |
    rg '^+' | # new additions only
    rg -i 'console\.|xxx:|\.only\('; then # grep for blocked strings
    echo >&2 "Blocking commit: a disallowed string was found"
    exit 1
fi
