#!/bin/sh
# adapted from https://stackoverflow.com/a/7292992

if git-diff-index -p -M --cached HEAD -- |
    rg '^+' |
    rg -i 'console\.|xxx:|\.only\('; then
    echo "Blocking commit: a disallowed string was found"
    exit 1
fi
