format = """
$time\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[env_var]
variable = "CURRENTSHELL"
default = "unknown"

[directory]
style = "blue"

[character]
success_symbol = "[\\$](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "purple"

[git_status]
format = " [[(*$conflicted$untracked$renamed$deleted$modified$staged)](218)[( $stashed)](165)( $ahead_behind)]($style)"
style = "cyan"
# conflicted = "​"
# untracked = "​"
# modified = "​"
# staged = "​"
# renamed = "​"
# deleted = "​"
stashed = "≡"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = " [$duration]($style) "
style = "yellow"

[time]
disabled = false
format = '[\[$time\]]($style) '
